// <auto-generated />
namespace IronCore.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class soososo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(soososo));
        
        string IMigrationMetadata.Id
        {
            get { return "202505251232243_soososo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
